### ISSUE TITLE
hard-coded installation path (--no-staged-install)

### ISSUE THREAD

**Issue by pcdi** [ChrisMuir/geoChina#3]
On this setup

```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6
```

I get the following error: `ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’`. So `geolocChina` has to be installed through `devtools::install_github("ChrisMuir/geolocChina", INSTALL_opts ="--no-staged-install")`.

**Comment by ChrisMuir** [comment]
Thank you for pointing this out, closed with [fbe926c](https://github.com/ChrisMuir/geolocChina/commit/fbe926c71dc0d2c611e26f45737ed9481f411e97).
